version: '2'
services:
  nginx:
    image: rbw0/nanio:nginx-arm32v7
    network_mode: host
    ports:
      - '80:80'
    environment:
      - NANIO_ADDRESS=127.0.0.1:8080
      - NGINX_RPS=2
      - NGINX_WORKERS=2
